# Generated by Django 2.1.3 on 2018-11-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateTimeField(verbose_name='date published')),
                ('active', models.BooleanField()),
                ('bio', models.TextField(max_length=300)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('website', models.URLField()),
                ('other', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='lab',
            name='manager',
            field=models.ManyToManyField(related_name='managers', to='dashboard.Member'),
        ),
        migrations.AddField(
            model_name='lab',
            name='researchers',
            field=models.ManyToManyField(related_name='researchers', to='dashboard.Member'),
        ),
    ]
