# Generated by Django 2.1.3 on 2018-11-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181109_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=750)),
                ('date_posted', models.DateTimeField(verbose_name='Date Posted')),
                ('tags', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='github',
        ),
        migrations.RemoveField(
            model_name='member',
            name='other',
        ),
        migrations.RemoveField(
            model_name='member',
            name='website',
        ),
        migrations.AddField(
            model_name='lab',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Date Completed'),
        ),
        migrations.AddField(
            model_name='lab',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Date Started'),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateTimeField(verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='executives',
            field=models.ManyToManyField(related_name='executives', to='dashboard.Member'),
        ),
        migrations.AddField(
            model_name='department',
            name='members',
            field=models.ManyToManyField(related_name='members', to='dashboard.Member'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Member'),
        ),
        migrations.AddField(
            model_name='lab',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Department'),
        ),
    ]
