# Generated by Django 2.1.3 on 2018-11-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181109_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
