# Generated by Django 2.1.3 on 2018-11-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20181109_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
