# Generated by Django 2.1.3 on 2018-11-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_member_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='full_name',
        ),
    ]
