# Generated by Django 2.1.3 on 2018-11-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20181109_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='linkedin',
        ),
    ]
