# Generated by Django 2.1.3 on 2018-11-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20181110_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='tags',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
