# Generated by Django 2.1.3 on 2018-11-11 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20181110_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date Started')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('blog_post', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='executives',
        ),
        migrations.RemoveField(
            model_name='department',
            name='members',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='department',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='researchers',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='start_date',
        ),
        migrations.AddField(
            model_name='lab',
            name='executives',
            field=models.ManyToManyField(related_name='executives', to='dashboard.Member'),
        ),
        migrations.AddField(
            model_name='lab',
            name='members',
            field=models.ManyToManyField(related_name='members', to='dashboard.Member'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='project',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Lab'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ManyToManyField(related_name='managers', to='dashboard.Member'),
        ),
        migrations.AddField(
            model_name='project',
            name='researchers',
            field=models.ManyToManyField(blank=True, related_name='researchers', to='dashboard.Member'),
        ),
    ]
