# Generated by Django 2.1.3 on 2018-11-11 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20181111_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='mentors',
            field=models.ManyToManyField(related_name='lab_mentors', to='dashboard.Member'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='executives',
            field=models.ManyToManyField(related_name='lab_executives', to='dashboard.Member'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='members',
            field=models.ManyToManyField(related_name='lab_members', to='dashboard.Member'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Lab'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to='dashboard.Member'),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='mentors',
            field=models.ManyToManyField(related_name='group_mentors', to='dashboard.Member'),
        ),
    ]
