# Generated by Django 2.1.3 on 2018-11-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20181111_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='executives',
        ),
        migrations.AddField(
            model_name='lab',
            name='directors',
            field=models.ManyToManyField(related_name='lab_directors', to='dashboard.Member'),
        ),
        migrations.AddField(
            model_name='lab',
            name='managers',
            field=models.ManyToManyField(related_name='lab_managers', to='dashboard.Member'),
        ),
    ]
