# Generated by Django 2.1.3 on 2018-11-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20181111_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='bio',
            new_name='description',
        ),
    ]
