# Generated by Django 2.1.3 on 2018-11-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20181114_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
