# Generated by Django 2.1.3 on 2018-11-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_project_in_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='manager',
            new_name='managers',
        ),
    ]
