# Generated by Django 2.1.3 on 2018-12-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20181120_0512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='bio',
            new_name='about',
        ),
    ]
