# Generated by Django 2.1.3 on 2018-12-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20181209_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='about',
            field=models.TextField(blank=True, default='', max_length=750),
        ),
    ]
