# Generated by Django 2.1.3 on 2018-12-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20181223_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
