# Generated by Django 2.1.3 on 2018-12-30 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_subgroup_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('SPRING', 'Spring'), ('FALL', 'Fall')], default='FALL', max_length=32)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Lab')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Member')),
            ],
        ),
    ]
