# Generated by Django 2.1.3 on 2018-12-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_executiverelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiverelationship',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
